application: mad-lids 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /_ah/login_required
  script: do_openid_login.app

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
